root: true
extends:
  - actano-base
  - plugin:import/typescript

plugins:
  - '@typescript-eslint'

parser: '@typescript-eslint/parser'

rules:
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - 'test/**/*.js'
  '@typescript-eslint/no-unused-vars': error
  import/prefer-default-export:
    - off
  import/extensions:
    - off
  '@typescript-eslint/no-shadow': error
  'no-shadow':
    - off

overrides:
  - files:
      - 'test/**/*.js'
    env:
      mocha: true
